In [9]:
import numpy as np 

size_of_array = 4
A = np.random.uniform(size = [size_of_array,size_of_array])
Q = np.matmul(A,A.T)

In [10]:
Q

array([[1.46916938, 1.83310226, 0.82223238, 1.28140937],
       [1.83310226, 2.51631422, 1.25120437, 1.56069122],
       [0.82223238, 1.25120437, 0.93782891, 0.68965693],
       [1.28140937, 1.56069122, 0.68965693, 1.18121036]])

In [11]:
for i in range(size_of_array):
    v = Q[:,i]
    v_adjoint = np.conjugate(v.T)
    holding = np.matmul(v_adjoint,Q)
    final = np.matmul(holding,v)
    if final < 0: 
        print("Error in Column " + str(i) + ". Halting Execution.")
    else:
        print("Q is postive and definite for vector " + str(i))

Q is postive and definite for vector 0
Q is postive and definite for vector 1
Q is postive and definite for vector 2
Q is postive and definite for vector 3


In [12]:
evalQ, evecQ = np.linalg.eig(Q)
a = np.matmul(evecQ,np.diag(evalQ)**0.5)
g = np.matmul(a,np.linalg.inv(evecQ))

print("The square root of matrix Q is: ")
print(g)

The square root of matrix Q is: 
[[0.76388912 0.71042285 0.23638521 0.57014401]
 [0.71042285 1.21087991 0.4924534  0.55033905]
 [0.23638521 0.4924534  0.77681177 0.18974737]
 [0.57014401 0.55033905 0.18974737 0.71921419]]


In [15]:
%timeit evecQ * np.diag(evalQ)**0.5 * evecQ


11.5 µs ± 1.98 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [16]:
%timeit evecQ @ np.diag(evalQ)**0.5 @ evecQ

11.2 µs ± 88.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [17]:
%timeit np.matmul(np.matmul(evecQ,np.diag(evalQ)**0.5),evecQ)

11.1 µs ± 33.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
